eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/,http://localhost:8082/eureka/
      
      
server:
  port: 8081
  
spring:
  application:
    name: eureka-client

    
  zipkin:
    base-url: http://localhost:8091