eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/,http://localhost:8082/eureka/
      
      
server:
  port: 8084
  
spring:
  application:
    name: pro-product
    
  zipkin:
    base-url: http://localhost:8091
