server:
  port: 8080
  
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl: 
      defaultZone: http://localhost:8082/eureka/

spring: 
  application: 
    name: eureka-server1
      